options(shiny.sanitize.errors = FALSE)
library(igraph)
library(rvest)
library(ade4)
library(corrplot)
library(ggplot2)
library(plotly)
library(factoextra)
library(geojsonio)
library(shinydashboard)
library(sp)
library(maps)
library(shiny)
library(corrplot)
library(tidyr)
library(dplyr)
library(shinyjs)
library(shinyBS)
library(scales)
library(DT)
library(plyr)
library(reshape)
library(data.table)
library(bit64)
library(rpart)
library(BBmisc)
library(maps)
library(rpart.plot)
library(FNN)
library(randomForest)
library(e1071)
library(dendextend)
library(ape)
library(RColorBrewer)
library(wordcloud)
library(tm)
library(SnowballC)
library(readr)
library(ggraph)
library(syuzhet)
library(algorithmia)
library(stringi)
library(text2vec)
library(smooth)
library(lubridate)
library(zoo)
library(dygraphs)
library(wordcloud2)
library(ggrepel)
library(topicmodels)
library(tidytext)
library(textclean)
library(leaflet)
library(fmsb)
library(shinycssloaders)
library(ggvis)
library(treemapify)
library(forecast)
library(highcharter)
library(prophet)
library(gutenbergr)
library(stringr)
library(shinyWidgets)
library(bsplus)
library(rintrojs)
library(shinydashboardPlus)
library(rvest)
library(countrycode)
library(pROC)
library(xgboost)
library(caret)

source('global_functions.R',local = TRUE)
source('shiny_functions.R',local = TRUE)

load('Saved/bikes.RData',envir =.GlobalEnv)
load('Saved/usa.RData',envir =.GlobalEnv)
load('Saved/hotel.RData',envir =.GlobalEnv)
load('Saved/sales.RData',envir = .GlobalEnv)
load('Saved/optim.RData',envir = .GlobalEnv)
load('Saved/pi.RData',envir = .GlobalEnv)
load('Saved/coins.RData',envir = .GlobalEnv)
load('Saved/markov.RData',envir = .GlobalEnv)


palettes = c('Spectral','RdYlGn','YlOrRd','Reds','Oranges','Greys','BuPu','Blues')
palettes_quali = c('Set1','Set2','Set3','Accent','Paired')
ep_cols = brewer.pal(n = 9, name = "Set1")
