# Install the packages needed for the App
list.of.packages <- c('rvest',
                      'ade4',
                      'factoextra',
                      "plotly",
                      'geojsonio',
                      "shinydashboard",
                      'sp',
                      "rpart.plot",
                      'maps',
                      'leaflet',
                      'shiny',
                      'corrplot',
                      'tidyr',
                      "dplyr",
                      "shinyjs",
                      "shinyBS",
                      "scales",
                      "DT",
                      "plyr",
                      "reshape",
                      "data.table",
                      "bit64",
                      "rpart",
                      "BBmisc",
                      # "gbm3",
                      'FNN',
                      'randomForest',
                      'e1071',
                      'dendextend',
                      'ape',
                      'maps',
                      'wordcloud',
                      'tm',
                      'SnowballC',
                      'RColorBrewer',
                      # 'RWeka',
                      'readr',
                      'igraph',
                      'ggraph',
                      'syuzhet',
                      'algorithmia',
                      'stringi',
                      'text2vec',
                      'glmnet',
                      'fastrtext',
                      'smooth',
                      'lubridate',
                      'zoo',
                      'dygraphs',
                      'wordcloud2',
                      'ggrepel',
                      'topicmodels',
                      'tidytext',
                      'textclean',
                      'fmsb',
                      'shinycssloaders',
                      'ggvis',
                      'treemapify',
                      'forecast',
                      'highcharter',
                      'prophet',
                      'gutenbergr',
                      'stringr',
                      'shinyWidgets',
                      'bsplus',
                      'rintrojs',
                      'pROC',
                      'shinydashboardPlus',
                      'xgboost',
                      'caret',
                      'visNetwork')
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages,dependencies = TRUE)
lapply(list.of.packages, require, character.only = TRUE)
